<?php
    require_once("criar_banco.php");
    require_once("criar_tabela.php");
    require_once("conexao.php");
    require_once("funcoes.php");
    require_once("pieces/header.php");
    require_once(organiza());
    require_once("pieces/footer.php");
?>